In [1]:
import numpy as np

In [2]:
#Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [3]:
#Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
a1 = a.reshape(2, 6)
a2 = a.reshape(4, 3)
a3 = a.reshape(6, 2)
a4 = a.reshape(12, 1)
a5 = a.reshape(3, 4)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [4]:
#Создать 5 двумерных массивов разной формы из массива a. 
#Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).
c1 = a.reshape(-1, 6)
c2 = a.reshape(-1, 4)
c3 = a.reshape(-1, 2)
c4 = a.reshape(12, -1)
c5 = a.reshape(4, -1)
print(c1)
print(c2)
print(c3)
print(c4)
print(c5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [5]:
#Если массив двумерный, можно вывести по номеру столбца и по номеру строки.
#Попоробуем вывести содержимое массива a по номеру строки и по номеру столбца.
try:
    print(a[0][0])
except IndexError:
    print('Error')
#Попробуем вывести содержимое массива с4 по номеру столбца и по номеру строки.
try:
    print(c4[0][0])
except IndexError:
    ('Error')
#При выводе одномерного массива a будет ошибка, при выводе массива с4 - ошибки нет. 
#Значит с4 - это двумерный массив, а массив  a - одномерный.

Error
12


In [9]:
#Создать массив из 3 строк и 4 столбцов, 
#состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, 
#равным 0 и среднеквадратичным отклонением, равным 1.0. 
#Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.
x = np.random.randn(3, 4)
print(x)
x1 = x.flatten()
print('*'*50)
print(x1)

[[-0.83885358  0.66937714  0.1614342  -0.57980642]
 [-1.18006572  0.67547853  1.25207836  0.63871137]
 [-2.01321967  0.42294449  0.2420175  -0.43812362]]
**************************************************
[-0.83885358  0.66937714  0.1614342  -0.57980642 -1.18006572  0.67547853
  1.25207836  0.63871137 -2.01321967  0.42294449  0.2420175  -0.43812362]


In [10]:
#Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [11]:
#Создать массив b, состоящий из 1 строки и 10 столбцов: 
#целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 
#В чем разница между массивами a и b?
b = (np.arange(20, 1, -2)).reshape(1, 10)
b
#Массив b является двумерным, массив a - одномерным.

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [12]:
#Вертикально соединить массивы a и b. a - двумерный массив из нулей, 
#число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, 
#состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.
a = np.zeros((2, 2))
b = np.ones((3, 2))
print(a)
print('*' * 50)
print(b)

[[0. 0.]
 [0. 0.]]
**************************************************
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
v = np.concatenate((a, b), axis = 0)
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
np.size(v)

10

In [15]:
#Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
#Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
#Получить матрицу At путем транспонирования матрицы A.
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [18]:
#Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [20]:
#Какой размер имеет матрица B? 
np.size(B), B.shape

(16, (4, 4))

In [21]:
#Получится ли вычислить обратную матрицу для матрицы B и почему?
########
#Если определитель матрицы равен нулю, то обратную матрицу посчитать невозможно.
#В этом случае определитель матрицы B равен нулю, поэтому ответ нет.
np.linalg.det(B)

0.0

In [22]:
#Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
np.random.seed(42)

In [23]:
#Создайте одномерный массив c, 
#составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [24]:
#Поменяйте его форму так, чтобы получилась квадратная матрица C. 
C = c.reshape(4, 4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [25]:
#Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. 
D = C*10 + B
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [26]:
#Определитель
d = np.linalg.det(D)
d

-28511999.999999944

In [27]:
#Ранг
r = np.linalg.matrix_rank(D)
r

4

In [28]:
#Обратная матрица
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

In [29]:
#Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
#Убедитесь, что в матрице D_inv остались только нули и единицы. 
D_inv = np.where(D_inv < 0, 0, 1)
D_inv

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

In [30]:
#С помощью функции numpy.where, используя матрицу D_inv в качестве маски, 
#а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  
#Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, 
#должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, 
#для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.
E = np.where(D_inv == 1, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])